app: tiny-site
requestLimit: 1024
# apiPrefix: /api
listen: ":7001"

# cookie track key
track: jt


# redis 配置(pass从env中获取pass这个配置为密码，如果未配置则为空)
redis: redis://127.0.0.1:6379

# postgres 配置 (pass从env中获取pass这个配置为密码，如果未配置则为空)
postgres:
  host: 127.0.0.1
  port: 5432
  user: vicanso 
  dbname: tiny
  password: 123456
  sslmode: disable

# session的相关配置
session:
  path: /
  key: tiny-site
  ttl: 24h

# key for sign cookie
keys:
  - cuttlefish
  - secret

location:
  baseURL: https://ip.aslant.site/

# router limit
routerLimit:
  # 限制路由访问并发数
  GET /users/v1/me/login: 50

# mail相关配置
mail:
  host: smtp.office365.com
  port: 587
  user: tree.xie@outlook.com
  password: EMAIL_PASS

# 告警接收邮件列表
alarm:
  receiver:
  - tree.xie@outlook.com

# tiny服务的配置
tiny:
  host: 127.0.0.1
  port: 6002

# token配置
token:
  innerUpdateImage: jLxzIivHSl

# 预览地址
imagePreview:
  url: "http://localhost:7001/images/v1/preview/:file"
